#!/usr/bin/env bash

DATE=$(date -u +"%Y-%m-%dT%T%z")
RUBY_VERSION=2.6.5
IMAGE_VERSION=3
VERSION="${RUBY_VERSION}-${IMAGE_VERSION}"

docker build --file image/base/Dockerfile . \
  --build-arg IMAGE_USER="rodeo" \
  --label "org.opencontainers.image.created=${DATE}" \
  --label "org.opencontainers.image.title=ruby-base" \
  --label "org.opencontainers.image.source=https://github.com/xe-gr/ruby-base-docker" \
  --label "org.opencontainers.image.version=${VERSION}" \
  --tag "xegr/ruby-base:${VERSION}" \
  --no-cache \
  --squash
