#!/usr/bin/env bash

DATE=$(date -u +"%Y-%m-%dT%T%z")
VERSION=2.6.5-1

docker build --file image/base/Dockerfile .  \
  --build-arg IMAGE_USER="rodeo" \
  --label "org.opencontainers.image.created=${DATE}" \
  --label "org.opencontainers.image.title=ruby-base" \
  --label "org.opencontainers.image.source=https://github.com/xe-gr/ruby-base-docker" \
  --label "org.opencontainers.image.version=${VERSION}" \
  --tag "xegr/ruby-base:${VERSION}"

docker push "xegr/ruby-base:${VERSION}"
